#  This is manual page in Perl POD format. Read more at
#  http://perldoc.perl.org/perlpod.html or run command:
#
#     perldoc perlpod | less
#
#  To check the syntax:
#
#     podchecker *.pod
#
#  Create manual page with command:
#
#    pod2man PAGE.N.pod > PAGE.N

=pod

=head1 NAME

program - Description

=head1 SYNOPSIS

  program [options]

=head1 OPTIONS

=over 4

=item B<-h>

Print available options.

=item B<-v>

Print the version number.

=back

=head1 DESCRIPTION

=head1 ENVIRONMENT

None.

=head1 FILES

None.

=head1 SEE ALSO

C<wmtime(1)>

=head1 AUTHORS

This manual page was written by Jari Aalto <jari.aalto@cante.net>, for
the Debian GNU system (but may be used by others). Updated by Jari
Aalto <jari.aalto@cante.net>. Released under GPL v2 or any later
version.

=cut
